### ISSUE TITLE
WorldEdit Beta 6+ incompatibility.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena_modules#1]
**Incompatibility for future release of WorldEdit.**

PVPArena compiled as of commit https://github.com/Eredrim/pvparena/commit/3ef4b52fd1161c4d727562f4d1cf2efcedb68dd2
PVPArena Modules compiled as of commit https://github.com/Eredrim/pvparena_modules/commit/a53cc34daaacdcc267cd6b2fe94a007f3ee86fed

With WorldEdit dev 4113, the WorldEdit module does not work and simply freezes the server when attempting to ``/pa arenaname regload battlefield``.

Downgrading to WorldEdit dev 4106, arena schematics load again.

Related issue: https://github.com/slipcor/pvparena_modules/issues/24#issuecomment-476412867
http://builds.enginehub.org/job/worldedit?branch=master

Assumed problem commits.
https://github.com/EngineHub/WorldEdit/commit/1934006d141612d5ae7bd2c92f686164ae8b42db / https://github.com/EngineHub/WorldEdit/commit/25631af31c1fc6ab029f2b6700e22d2e77819cda

**Comment by mibby** [comment]
Do you think it would be possible to get a test build of the worldedit module with a fix for when the next beta version _is_ released? PVPArena is the only thing holding me back from continuing to use and test the latest worldedit dev builds. :(

**Comment by Eredrim** [comment]
It works perfectly with WorldEdit 7.0 RC3 and above.
