### ISSUE TITLE
[Module - LateLounge] Command to leave queue.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena_modules#3]
Currently when you enter an arena queue, it does not tell you the status of the queue in regards to how many players it is waiting for to begin and you aren't able to leave the queue once in it (as far as I can tell). Typing ``/pa leave`` just outputs you aren't in an arena.

Would it be possible to add a command to check queue status and a command to be able to leave the queue so you aren't put in a game hours later at random?

Perhaps even a queue timeout if no game is formed after so long?

**Comment by Eredrim** [comment]
@mibby I implemented `/pa leave` command in order to leave LateLounge queue. Hoping it will be right for you.

To check status, you can just type `/pa <arena>` again.
